// export const skills = [
//   'JAVASCRIPT',
//   'HTML & CSS',
//   'REACT',
//   'REACT-REDUX',
//   'REDUX-SAGA',
//   'REDUX-FORM',
//   'REACT-HOOK-FORM',
//   'FORMIK',
//   'YUP',
//   'MUI',
//   'TYPESCRIPT',
//   'NEXT.JS',
//   'JEST',
//   'MSW',
//   'NODE.JS',
//   'EXPRESS',
//   'JWT & BCRYPT',
//   'JOI',
//   'AJV',
//   'SWAGGER',
//   'JSDOC',
//   'MONGODB',
//   'MONGOOSE',
//   'GIT',
//   'STORYBOOK',
// ];
export const skills = [
  'Javascript',
  'Html & Css',
  'React',
  'React-Redux',
  'Redux-Saga',
  'Redux-Form',
  'React-Hook-Form',
  'Formik',
  'Yup',
  'Mui',
  'Typescript',
  'Next.Js',
  'Jest',
  'Msw',
  'Node.Js',
  'Express',
  'Jwt & Bcrypt',
  'Joi',
  'Ajv',
  'Swagger',
  'Jsdoc',
  'Mongodb',
  'Mongoose',
  'Git',
  'Storybook',
];

export const weatherAppTools = [
  'React',
  'Context Api',
  'Hooks',
  'React-Redux',
  'React Router',
  'React-Hook-Form',
  'Scss Modules',
  'Typescript',
  'Jest',
  'React Testing Library',
  'Git',
  'Github',
];

export const interiorProjectTools = [
  'React',
  'Context Api',
  'Hooks',
  'React Router',
  'Formik',
  'Scss Modules',
  'Node.Js',
  'Express',
  'Jwt & Bcrypt',
  'Git',
  'Github',
];
