#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
. "$(dirname -- "$0")/colors"

hook_name="Husky pre-push hook"

printf "\n%b[STARTED]%b %s\n" "$cg" "$co" "$hook_name"

branch_name="$(git rev-parse --abbrev-ref HEAD)"

if ! echo "$branch_name" ; then
  printf "%b[FAILED]%b %s:\n" "${cr}" "$co" "$hook_name"
  printf "  - branch name: %b\"$branch_name\"%b\n" "${cr}" "$co"

  exit 1
fi

printf "%b[SUCCESS]%b %b\n\n" "$cg" "$co" "$hook_name"
